name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: 'servicebus-emulator'
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - './config.json:/ServiceBus_Emulator/ConfigFiles/Config.json'
    ports:
      - '5672:5672'
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: 'Abd@123456!'
      ACCEPT_EULA: 'Y'
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - 'sb-emulator'
  sqledge:
    container_name: 'sqledge'
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    networks:
      sb-emulator:
        aliases:
          - 'sqledge'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Abd@123456!'
networks:
  sb-emulator:
