---
openapi: 3.0.0
info:
  title: n8n Public API
  description: n8n Public API
  termsOfService: https://n8n.io/legal/terms
  contact:
    email: hello@n8n.io
  license:
    name: Sustainable Use License
    url: https://github.com/n8n-io/n8n/blob/master/packages/cli/LICENSE.md
  version: v1
externalDocs:
  description: n8n API documentation
  url: https://docs.n8n.io/api/
servers:
  - url: /api/v1
tags:
- name: User
  description: Operations about user
- name: Execution
  description: Operations about execution
- name: Workflow
  description: Operations about workflow
paths:
  /users:
    $ref: './spec/paths/Users.yml'
  /users/{identifier}:
    $ref: './spec/paths/UserById.yml'
  /executions:
    $ref: './spec/paths/Executions.yml'
  /executions/{executionId}:
    $ref: './spec/paths/ExecutionById.yml'
  /workflows:
    $ref: './spec/paths/Workflows.yml'
  /workflows/{workflowId}:
    $ref: './spec/paths/WorkflowById.yml'
  /workflows/{workflowId}/activate:
    $ref: './spec/paths/WorkflowByIdActivate.yml'
  /workflows/{workflowId}/deactivate:
    $ref: './spec/paths/WorkflowByIdDeactivate.yml'
components:
  schemas:
    $ref: './spec/schemas/_index.yml'
  responses:
    $ref: './spec/responses/_index.yml'
  parameters:
    $ref: './spec/parameters/_index.yml'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-N8N-API-KEY

security:
  - ApiKeyAuth: []
