services:
  n8n:
    image: ghcr.io/n8n-io/n8n:${N8N_VERSION:-latest}
    environment:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_USER_FOLDER=/n8n
      - DB_SQLITE_POOL_SIZE=3
      - DB_SQLITE_ENABLE_WAL=true
    ports:
      - 5678:5678
    volumes:
      - /n8n:/n8n
  benchmark:
    image: ghcr.io/n8n-io/n8n-benchmark:${N8N_BENCHMARK_VERSION:-latest}
    depends_on:
      - n8n
    environment:
      - N8N_BASE_URL=http://n8n:5678
      - K6_API_TOKEN=${K6_API_TOKEN}
