required:
  - name
  - type
  - data
type: object
properties:
  id:
    type: string
    readOnly: true
    example: R2DjclaysHbqn778
  name:
    type: string
    example: Joe's Github Credentials
  type:
    type: string
    example: githubApi
  data:
    type: object
    writeOnly: true
    example: { accessToken: 'ada612vad6fa5df4adf5a5dsf4389adsf76da7s' }
  isResolvable:
    type: boolean
    example: false
    description: Whether this credential has resolvable fields
  createdAt:
    type: string
    format: date-time
    readOnly: true
    example: '2022-04-29T11:02:29.842Z'
  updatedAt:
    type: string
    format: date-time
    readOnly: true
    example: '2022-04-29T11:02:29.842Z'
