type: object
properties:
  name:
    type: string
    example: Joe's Github Credentials
  type:
    type: string
    example: githubApi
  data:
    type: object
    writeOnly: true
    description: Partial credential data object. Redacted fields may be sent and will be unredacted using stored values.
    example: { accessToken: 'ada612vad6fa5df4adf5a5dsf4389adsf76da7s' }
  isResolvable:
    type: boolean
    example: false
    description: Whether this credential has resolvable fields
  isGlobal:
    type: boolean
    example: false
    description: Whether this credential is shared globally (requires license + scope
