name: Check Issue Template

on:
  issues:
    types: [opened, edited]

jobs:
  check-issue:
    name: Check Issue Template
    runs-on: ubuntu-latest
    steps:
      - name: Run Check Issue Template
        uses: n8n-io/validate-issue-template-content@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
