name: PR Checklist

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - master
  workflow_dispatch:

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist job
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Checklist
        uses: n8n-io/contextual-qa-checklist-action@v1.0.0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          comment-footer: Make sure to check off this list before asking for review.
