name: Docker Image CI - Rpi

on:
  push:
    tags:
      - n8n@*

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 (Rpi)
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build --platform linux/arm/v7 --build-arg N8N_VERSION=${{steps.vars.outputs.tag}} -t n8nio/n8n:${{steps.vars.outputs.tag}}-rpi --output type=image,push=true docker/images/n8n-rpi
