name: Docker Nightly Image CI

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository to create image off.'
        required: true
        default: 'n8n-io/n8n'
      branch:
        description: 'GitHub branch to create image off.'
        required: true
        default: 'master'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'nightly'
      merge-master:
        description: 'Merge with master.'
        type: boolean
        required: true
        default: false
      success-url:
        description: 'URL to call after Docker Image got built successfully.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository || 'n8n-io/n8n' }}
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Merge Master - optionally
        run: |
          [[ "${{github.event.inputs.merge-master}}" == "true" ]] && git remote add upstream https://github.com/n8n-io/n8n.git -f; git merge upstream/master --allow-unrelated-histories || echo ""
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/images/n8n-custom/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n:${{ github.event.inputs.tag || 'nightly' }}
          no-cache: true

      - name: Call Success URL - optionally
        run: |
          [[ "${{github.event.inputs.success-url}}" != "" ]] && curl -v ${{github.event.inputs.success-url}} || echo ""
        shell: bash
