name: End-to-End tests
run-name: E2E Tests ${{ inputs.branch }} - ${{ inputs.user }}

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to test.'
        required: false
        default: 'master'
      user:
        description: 'User who kicked this off.'
        required: false
        default: 'schedule'
      start-url:
        description: 'URL to call after workflow is kicked off.'
        required: false
        default: ''
      success-url:
        description: 'URL to call after workflow is done.'
        required: false
        default: ''

jobs:
  calls-start-url:
    name: Calls start URL
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.start-url != '' }}
    steps:
      - name: Calls start URL
        run: |
          [[ "${{github.event.inputs.start-url}}" != "" ]] && curl -v -X POST -d 'url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}' ${{github.event.inputs.start-url}} || echo ""
        shell: bash

  e2e-node-16:
    name: E2E[Electron/Node 16]
    # TODO: Change to master branch before merge
    uses: n8n-io/n8n/.github/workflows/e2e-reusable.yml@parallel_e2e_sorry_cy
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-e2e') }}
    with:
      # TODO: Change to master branch before merge
      branch: ${{ github.event.inputs.branch || 'parallel_e2e_sorry_cy' }}
      user: ${{ github.event.inputs.user || 'PR User' }}
      spec: ${{ github.event.inputs.spec || 'e2e/*' }}
      run-env: base:16.18.1
    secrets:
      CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
  e2e-node-14:
    name: E2E[Electron/Node 14]
    uses: n8n-io/n8n/.github/workflows/e2e-reusable.yml@parallel_e2e_sorry_cy
    with:
      branch: ${{ github.event.inputs.branch || 'parallel_e2e_sorry_cy' }}
      user: ${{ github.event.inputs.user || 'schedule' }}
      spec: ${{ github.event.inputs.spec || 'e2e/*' }}
      run-env: base:14.21.1
    secrets:
      CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}

  calls-success-url-notify:
    name: Calls success URL and notifies
    runs-on: ubuntu-latest
    needs: [e2e-node-16, e2e-node-14]
    if: ${{ github.event.inputs.success-url != '' }}
    steps:
      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          channel: '#updates-build-alerts'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: E2E failure for branch `${{ inputs.branch || 'master' }}` deployed by ${{ inputs.user || 'schedule' }} (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Call Success URL - optionally
        run: |
          [[ "${{github.event.inputs.success-url}}" != "" ]] && curl -v ${{github.event.inputs.success-url}} || echo ""
        shell: bash
