name: PR E2E

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: e2e-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  job-get-metadata:
    name: Get Metadata
    runs-on: ubuntu-20.04
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Determine changed files
        uses: dorny/paths-filter@v3.0.1
        id: changed
        with:
          filters: |
            ignored:
              - '!.devcontainer/**'
              - '!.github/*'
              - '!.github/scripts/*'
              - '!.github/workflows/benchmark-*'
              - '!.github/workflows/check-*'
              - '!.vscode/**'
              - '!docker/**'
              - '!packages/@n8n/benchmark/**'
              - '!**/*.md'
          predicate-quantifier: 'every'

    outputs:
      # The e2e tests should run when:
      # - It has changes to files that are not ignored
      # - It is not a community PR
      # - It is targeting master or a release branch
      should_run_e2e: ${{ steps.changed.outputs.ignored == 'true' && !contains(github.event.pull_request.labels.*.name, 'community') && (github.event.pull_request.base.ref == 'master' || startsWith(github.event.pull_request.base.ref, 'release/')) }}
      # has_testable_files: ${{ steps.changed.outputs.ignored == 'true' }}
      # is_community_pr: ${{ contains(github.event.pull_request.labels.*.name, 'community') }}
      # is_target_master: ${{ github.event.pull_request.base.ref == 'master' }}
      # is_target_release: ${{ startsWith(github.event.pull_request.base.ref, 'release/') }}

  run-e2e-tests:
    name: E2E [Electron/Node 18]
    needs: [job-get-metadata]
    uses: ./.github/workflows/e2e-reusable.yml
    if: ${{ github.event.review.state == 'approved' && needs.job-get-metadata.outputs.should_run_e2e == 'true' }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
      user: ${{ github.event.pull_request.user.login || 'PR User' }}
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  post-e2e-tests:
    runs-on: ubuntu-latest
    name: E2E [Electron/Node 18] - Checks
    needs: [job-get-metadata, run-e2e-tests]
    if: always()
    steps:
      - name: E2E success comment
        if: ${{ needs.job-get-metadata.outputs.should_run_e2e == 'true' && needs.run-e2e-tests.outputs.tests_passed == 'true' }}
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :white_check_mark: All Cypress E2E specs passed
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: E2E fail comment
        if: needs.run-e2e-tests.result == 'failure'
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :warning: Some Cypress E2E specs are failing, please fix them before merging
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Success job if community PR
        if: ${{ contains(github.event.pull_request.labels.*.name, 'community') }}
        run: exit 0

      - name: Fail job if run-e2e-tests failed
        if: ${{ (github.event.review.state != 'approved' && github.event.review.state != 'commented') || needs.run-e2e-tests.result == 'failure' }}
        run: exit 1
