name: 'Test: Benchmark Destroy Env'

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: benchmark
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: benchmarking

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ secrets.BENCHMARK_ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.BENCHMARK_ARM_TENANT_ID }}
          subscription-id: ${{ secrets.BENCHMARK_ARM_SUBSCRIPTION_ID }}

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          build-command: ''

      - name: Destroy cloud env
        run: pnpm destroy-cloud-env
        working-directory: packages/@n8n/benchmark
